main/urls.py
from filebrowser.sites import site

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from main.views import ContactsView, PageView, CallView, ReviewsView, FeedbackView
from shop.views import (
    ItemList, 
    ItemDetail,
    CartDetail,
    CartAdd,
    CartDelete,
    CartPlus,
    CartMinus,
    CartDiscounts,
    OrderCreate,
    OrderPayment,
    OrderPaymentOk,
    OrderPaymentNo,
    OrderList,
    OrderDetail,
    BuyOneClick,
    )
from articles.views import ArticleList, ArticleDetail
from users.views import (
    LoginView, 
    LogoutView, 
    RegistrationView, 
    RegistrationCompleteView, 
    ResetPasswordView,
    ResetPasswordCompleteView,
    ProfileView,
    ProfileUpdateView,
    ChangePasswordView,
    ProfileMemberCreateView,
    ProfileMemberUpdateView
    )


urlpatterns = [
    url(r'^$', ItemList.as_view(), name='index'),
    url(r'^contacts/$', ContactsView.as_view(), name='contacts'),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^registration/(?P<uuid>.*)/$', RegistrationCompleteView.as_view(), name='registration-complete'),
    url(r'^reset/password/$', ResetPasswordView.as_view(), name='reset-password'),
    url(r'^reset/password/(?P<uuid>.*)/$', ResetPasswordCompleteView.as_view(), name='reset-password-complete'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/update/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^change/password/$', ChangePasswordView.as_view(), name='change-password'),
    url(r'^profile/member/create/$', ProfileMemberCreateView.as_view(), name='profile-member-create'),
    url(r'^profile/member/update/(?P<pk>[0-9]+)/$', ProfileMemberUpdateView.as_view(), name='profile-member-update'),
    url(r'^reviews/$', ReviewsView.as_view(), name='reviews'),

    url(r'^buy/$', BuyOneClick.as_view(), name='buy-one-click'),
    url(r'^call/$', CallView.as_view(), name='call'),
    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),

    url(r'^category/$', ArticleList.as_view(), name='articles'),
    url(r'^category/(?P<slug>[-_\w]+)/$', ArticleList.as_view(), name='articles'),
    url(r'^articles/(?P<slug>[-_\w]+)/$', ArticleDetail.as_view(), name='articles-detail'),

    url(r'^catalog/(?P<slug>[-_\w]+)/$', ItemList.as_view(), name='items'),
    url(r'^items/(?P<slug>[-_\w]+)/$', ItemDetail.as_view(), name='items-detail'),
    url(r'^cart/$', CartDetail.as_view(), name='cart-detail'),
    url(r'^order/$', OrderCreate.as_view(), name='order-create'),
    url(r'^order/payment/ok/$', OrderPaymentOk.as_view(), name='order-payment-ok'),
    url(r'^order/payment/no/$', OrderPaymentNo.as_view(), name='order-payment-no'),
    url(r'^order/payment/(?P<pk>[0-9]+)/$', OrderPayment.as_view(), name='order-payment'),
    url(r'^order/list/$', OrderList.as_view(), name='order-list'),
    url(r'^order/detail/(?P<pk>[0-9]+)/$', OrderDetail.as_view(), name='order-detail'),

    url(r'^ajax/cart/plus/$', CartPlus.as_view(), name='ajax-cart-plus'),
    url(r'^ajax/cart/minus/$', CartMinus.as_view(), name='ajax-cart-minus'),
    url(r'^ajax/cart/add/$', CartAdd.as_view(), name='ajax-cart-add'),
    url(r'^ajax/cart/delete/$', CartDelete.as_view(), name='ajax-cart-delete'),
    url(r'^ajax/cart/discounts/$', CartDiscounts.as_view(), name='ajax-cart-discounts'),
    
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^social/', include('social_auth.urls')),

    url(r'^(?i)robots\.txt$', 'main.views_seo.robots_txt', name='robots'),
    url(r'^(?i)sitemap\.xml$', 'main.views_seo.sitemap_xml', name='sitemap_xml'),
    url(r'^(?i)sitemap-(?P<section>.+)\.xml$', 'main.views_seo.sitemap_xml', name='sitemap-section'),
]


if settings.DEBUG:
    urlpatterns += [ 
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    ]


urlpatterns += [   
    url(r'^(?P<url>.*/)$', PageView.as_view(), name='pages'),
]

articles/models.py
#-*- encoding: utf-8 -*-
import os
from ckeditor_uploader.fields import RichTextUploadingField

from django.db import models
from django.utils.translation import ugettext_lazy as _ul

from main.models import SeoBaseModel


class Category(SeoBaseModel):
    description = RichTextUploadingField(verbose_name=_ul(u'Описание'), null=True, blank=True)

    class Meta:
        verbose_name = _ul(u'Категория')
        verbose_name_plural = _ul(u'Категории')

    def __unicode__(self):
        return u'%s' % self.title


def img_upload_to(instance, filename):
    UPLOAD_PATH = 'uploads/articles/'
    return os.path.join(UPLOAD_PATH, instance.slug, filename)


class Article(SeoBaseModel):
    img = models.ImageField(verbose_name=_ul(u'Картинка'), upload_to=img_upload_to, null=True, blank=True)
    alt = models.CharField(verbose_name=_ul(u'Alt картинки'), max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name=_ul(u'Категория'))
    announcement = RichTextUploadingField(verbose_name=_ul(u'Анонс'), null=True, blank=True)
    description = RichTextUploadingField(verbose_name=_ul(u'Описание'), null=True, blank=True)

    class Meta:
        verbose_name = _ul(u'Статья')
        verbose_name_plural = _ul(u'Статьи')

    def __unicode__(self):
        return u'%s' % self.title

shop/models.py
#-*- encoding: utf-8 -*-
import os
from ckeditor_uploader.fields import RichTextUploadingField

from django.db import models
from django.utils.translation import ugettext_lazy as _ul
from django.forms.models import model_to_dict
from django.core.exceptions import ValidationError

from main.models import SeoBaseModel, DateBaseModel
from users.models import User


class Catalog(SeoBaseModel):
    description = RichTextUploadingField(verbose_name=_ul(u'Описание'), null=True, blank=True)
    sorting = models.PositiveIntegerField(verbose_name=_ul(u'Сортировка'), default=0)

    class Meta:
        verbose_name = _ul(u'Каталог')
        verbose_name_plural = _ul(u'Каталоги')

    def __unicode__(self):
        return u'%s' % self.title


class ItemManager(models.Manager):
    pass


class Item(SeoBaseModel):
    catalog = models.ForeignKey(Catalog, verbose_name=_ul(u'Каталог'))
    description = RichTextUploadingField(verbose_name=_ul(u'Описание'), null=True, blank=True)
    price = models.DecimalField(verbose_name=_ul(u'Цена'), default=0.0, max_digits=10, decimal_places=0)
    sorting = models.PositiveIntegerField(verbose_name=_ul(u'Сортировка'), default=0)

    objects = ItemManager()

    @property
    def image(self):
        return ItemImage.objects.filter(item=self, is_main=True).first()

    @property
    def images(self):
        return ItemImage.objects.filter(item=self)

    @property
    def parts(self):
        return ItemPart.objects.filter(item=self)

    class Meta:
        verbose_name = _ul(u'Товар')
        verbose_name_plural = _ul(u'Товары')

    def __unicode__(self):
        return u'%s' % self.title


def img_upload_to(instance, filename):
    UPLOAD_PATH = 'uploads/items/'
    return os.path.join(UPLOAD_PATH, instance.item.slug, filename)


class ItemImage(DateBaseModel):
    item = models.ForeignKey(Item, verbose_name=_ul(u'Товар'))
    is_main = models.BooleanField(verbose_name=_ul(u'Главная?'), default=False)
    img = models.ImageField(verbose_name=_ul(u'Картинка'), upload_to=img_upload_to)
    alt = models.CharField(verbose_name=_ul(u'Alt картинки'), max_length=255, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.is_main:
            self.__class__.objects.filter(item=self.item).update(is_main=False)
        return super(ItemImage, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _ul(u'Картинка товара')
        verbose_name_plural = _ul(u'Картинки товара')

    def __unicode__(self):
        return u'%s: %s' % (self.item.title, self.img)


class ItemPart(DateBaseModel):
    item = models.ForeignKey(Item, verbose_name=_ul(u'Товар'))
    name = models.CharField(verbose_name=_ul(u'Наименование'), max_length=255)
    count = models.PositiveIntegerField(verbose_name=_ul(u'Кол-во'), default=0)

    class Meta:
        verbose_name = _ul(u'Состав товара')
        verbose_name_plural = _ul(u'Состав товара')

    def __unicode__(self):
        return u'%s: %s' % (self.item.title, self.name)


class Discount(DateBaseModel):
    DISCOUNT_ACTION_AUTH = 0
    DISCOUNT_ACTION_FAMILY_BIRTHDAY = 1
    DISCOUNT_ACTION_PRE_ORDER = 2
    DISCOUNT_ACTIONS = (
        (DISCOUNT_ACTION_AUTH, _ul(u'Скидка для авторизованного пользователя')),
        (DISCOUNT_ACTION_FAMILY_BIRTHDAY, _ul(u'Скидка в день рождения члена семьи')),
        (DISCOUNT_ACTION_PRE_ORDER, _ul(u'Скидка на предварительный заказ')),
    )

    # DISCOUNT_PERCENTAGE = 0
    # DISCOUNT_AMOUNT = 1
    # DISCOUNT_TYPES = (
    #     (DISCOUNT_PERCENTAGE, _ul(u'Скидка в процентах')),
    #     (DISCOUNT_AMOUNT, _ul(u'Скидка в рублях')),
    # )

    action = models.PositiveIntegerField(verbose_name=_ul(u'Вариант скидки'), choices=DISCOUNT_ACTIONS, unique=True)
    #discount_type = models.PositiveIntegerField(verbose_name=_ul(u'Тип скидки'), default=DISCOUNT_PERCENTAGE, choices=DISCOUNT_TYPES)
    amount = models.DecimalField(verbose_name=_ul(u'Скидка в %'), default=0.0, max_digits=10, decimal_places=0)
    active = models.BooleanField(verbose_name=_ul(u'Активирована?'), default=False)

    class Meta:
        verbose_name = _ul(u'Скидка')
        verbose_name_plural = _ul(u'Скидки')

    def __unicode__(self):
        return u'%s - %s' % (self.get_action_display(), self.amount)


class Order(DateBaseModel):
    ORDER_STATUS_NEW = 0
    ORDER_STATUS_PAYMENT = 1
    ORDER_STATUS_COMPLETED = 2
    ORDER_STATUSES = (
        (ORDER_STATUS_NEW, _ul(u'Новый')),
        (ORDER_STATUS_PAYMENT, _ul(u'Оплаченный')),
        (ORDER_STATUS_COMPLETED, _ul(u'Завершенный')),
    )

    DELIVERY_SELF = 0
    DELIVERY_DOOR = 1
    DELIVERY_TYPES = (
        (DELIVERY_SELF, _ul(u'Самовывоз')),
        (DELIVERY_DOOR, _ul(u'Доставка до двери')),
    )

    PAYMENT_CASH = 0
    PAYMENT_CREDIT_CARD = 1
    PAYMENT_ECOMMERCE = 2
    PAYMENT_TYPES = (
        (PAYMENT_CASH, _ul(u'Наличные')),
        (PAYMENT_CREDIT_CARD, _ul(u'Банковская карта')),
        (PAYMENT_ECOMMERCE, _ul(u'Электронные деньги')),
    )

    user = models.ForeignKey(User, verbose_name=_ul(u'Пользователь'), null=True, blank=True)
    first_name = models.CharField(verbose_name=_ul(u'Имя'), max_length=255)
    last_name = models.CharField(verbose_name=_ul(u'Фамилия'), max_length=255, null=True, blank=True)
    phone = models.CharField(verbose_name=_ul(u'Номер телефона (+79101010101)'), max_length=255, null=True, blank=True)
    email = models.EmailField(verbose_name=_ul(u'Адрес электронной почты'), max_length=255, null=True, blank=True)
    delivery_type = models.PositiveIntegerField(verbose_name=_ul(u'Вариант доставки'), default=DELIVERY_SELF, choices=DELIVERY_TYPES)
    delivery = models.TextField(verbose_name=_ul(u'Адрес доставки'), null=True, blank=True)
    delivery_date = models.DateTimeField(verbose_name=_ul(u'Дата доставки'), null=True, blank=True)
    payment_type = models.PositiveIntegerField(verbose_name=_ul(u'Вариант оплаты'), default=PAYMENT_CASH, choices=PAYMENT_TYPES)
    note = models.TextField(verbose_name=_ul(u'Комментарии'), null=True, blank=True)

    items_count = models.PositiveIntegerField(verbose_name=_ul(u'Кол-во'), null=True, blank=True)
    items_price = models.DecimalField(verbose_name=_ul(u'Цена'), max_digits=10, decimal_places=0, null=True, blank=True)
    items_discount = models.DecimalField(verbose_name=_ul(u'Скидка в %'), max_digits=10, decimal_places=0, null=True, blank=True)
    items_price_with_discount = models.DecimalField(verbose_name=_ul(u'Цена cо скидкой'), max_digits=10, decimal_places=0, null=True, blank=True)

    status = models.PositiveIntegerField(verbose_name=_ul(u'Статус'), default=ORDER_STATUS_NEW, choices=ORDER_STATUSES)

    items = models.ManyToManyField(Item, verbose_name=_ul(u'Товары'), through='OrderItem', blank=True)

    @property
    def order_items(self):
        return OrderItem.objects.filter(order=self)

    def clean(self):
        if not self.email and not self.phone:
            raise ValidationError(_ul(u'Телефон или почта должны быть заполнены.'))

    class Meta:
        verbose_name = _ul(u'Заказ')
        verbose_name_plural = _ul(u'Заказы')

    def __unicode__(self):
        return u'%s: %s %s - %s' % (self.creation_date, self.first_name, self.last_name, self.get_status_display())


class OrderItemManager(models.Manager):

    def get_cart(self, request, is_dict=False):
        #request.session['cart'] = {}
        order = Order()
        cart = request.session.get('cart', {})
        items = Item.objects.filter(pk__in=cart.keys())
        order_items = []
        for item in items:
            order_item = OrderItem(
                order=order,
                item=item,
                item_catalog=item.catalog,
                item_title=item.title,
                item_description=item.description,
                item_price=item.price,
                count=cart[str(item.pk)]
                )
            if is_dict:
                order_item = model_to_dict(order_item)
                order_item['item'] = model_to_dict(item)
                order_item['order'] = model_to_dict(order)
            order_items.append(
                order_item
                )
        return order_items


class OrderItem(DateBaseModel):
    order = models.ForeignKey(Order, verbose_name=_ul(u'Заказ'))
    item = models.ForeignKey(Item, verbose_name=_ul(u'Товар'))

    item_catalog = models.ForeignKey(Catalog, verbose_name=_ul(u'Каталог'))
    item_title = models.CharField(verbose_name=_ul(u'Заголовок'), max_length=255)
    item_description = RichTextUploadingField(verbose_name=_ul(u'Описание'), null=True, blank=True)
    item_price = models.DecimalField(verbose_name=_ul(u'Цена'), default=0.0, max_digits=10, decimal_places=0)

    count = models.PositiveIntegerField(verbose_name=_ul(u'Кол-во'), default=1)

    objects = OrderItemManager()

    class Meta:
        verbose_name = _ul(u'Товар заказа')
        verbose_name_plural = _ul(u'Товары заказа')
        unique_together = ('order', 'item')

    def __unicode__(self):
        return u'%s / %s' % (self.order, self.item)

articles/views.py
#-*- encoding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from main.mixins import SeoMixin
from articles.models import Category, Article


class ArticleList(SeoMixin, ListView):
    template_name = 'main/articles.html'
    paginate_by = 10
    model = Article

    def get_queryset(self):
        qs = super(ArticleList, self).get_queryset()
        qs = qs.filter(is_published=True, category__is_published=True)
        qs = qs.filter(category=self.category).order_by('-creation_date')
        return qs

    def get_context_data(self, **kwargs):
        kwargs = super(ArticleList, self).get_context_data(**kwargs)
        kwargs['object'] = self.category
        kwargs = self.get_context_seo_data(**kwargs) 
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        slug = kwargs.get('slug', None)
        if slug is None:
            self.category = Category.objects.filter(is_published=True).first()
        else:
            self.category = get_object_or_404(Category, slug=slug, is_published=True)
        return super(ArticleList, self).dispatch(request, *args, **kwargs)


class ArticleDetail(SeoMixin, DetailView):
    template_name = 'main/article.html'
    model = Article

    def get_object(self, queryset=None):
        qs = self.model.objects.all()
        qs = qs.filter(is_published=True)
        return super(ArticleDetail, self).get_object(queryset=qs)

    def get_context_data(self, **kwargs):
        kwargs = super(ArticleDetail, self).get_context_data(**kwargs)
        kwargs = self.get_context_seo_data(**kwargs) 
        return kwargs

main/templates/main/articles.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load main_tags %}
{% load humanize %}
{% load staticfiles %}

{% block body_class %}i-articles{% endblock %}


{% block content %}
    <header class="header">
        <img class="header_img img-responsive" src="{% static 'main/img/articles.jpg' %}" alt="" />
    </header>

    <div class="main">
        <div class="container">
            <div class="row">
                <div class="title-holder col-lg-12">
                    <h1>Статьи</h1>
                </div>  <!-- /.title-holder -->
            </div>  <!-- /.row -->
                
            <div class="row">
                {% for article in object_list %}
                <article class="article col-md-4 col-sm-6">
                    <div class="article_date">{{article.creation_date|naturaltime}}</div>
                    
                    <h2>{{article.title}}</h2>
                    
                    <p>{{article.announcement|safe}}</p>
                    
                    <a class="article_readmore" href="{% url 'articles-detail' article.slug %}">Подробнее</a>
                </article>  <!-- /.article -->
                {% endfor %}
            </div>  <!-- /.row -->

            <div class="row text-center">
                {% block pagination %}
                {% if page_obj.paginator.num_pages > 1 %}
                <ul class="pagination col-lg-12">
                    {% for num_page in page_obj.paginator.num_pages|range %}
                    <li class="{% if num_page == page_obj.number %}active{% endif %}"><a href="?page={{num_page}}">{{num_page}}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endblock %}
            </div>
        </div>  <!-- /.container -->
    </div>  <!-- /.main -->

{% endblock %}

main/templates/main/base-presentation.html
{% extends 'main/base.html' %}


{% block presentation %}
    {% if not hide_presentation %}
    {% if carousel %}
    <header class="header">
        <div id="slides" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for item in carousel.get_items %}
                <li class="indicators_item {% if forloop.first %}active{% endif %}" data-slide-to="{{forloop.counter0}}" data-target="#slides"></li>
                {% endfor %}
            </ol>

            <div class="carousel-inner" role="listbox">
                {% for item in carousel.get_items %}
                <div class="slides_item item {% if forloop.first %}active{% endif %}"><a href="{{item.link}}" class=""><img class="img-responsive center-block" src="{{item.img.url}}" alt="{{item.alt}}" /></a></div>
                {% endfor %}
            </div>
            
            <div class="container pos-rel">
                <a class="left carousel-control" data-slide="prev" role="button" href="#slides"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
                <a data-slide="next" role="button" href="#slides" class="right carousel-control"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a>
            </div>
        </div>  <!-- /.carousel -->
    </header>   <!-- /.header -->
    {% endif %}
    {% else %}
    <header class="header"></header>
    {% endif %}
{% endblock %}

main/templates/main/order-create-cart.html
{% load i18n %}
{% load main_tags %}

<table class="orderpage_table">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Товар</th>
            <th>Кол-во</th>
            <th>Цена</th>
            {% if cart.items_discount %}
            <th>Со скидкой</th>
            {% endif %}
        </tr>
    </thead>
    
    <tbody>
        {% for item in cart.items %}
        <tr>
            <td><a href="{% url 'items-detail' item.item.slug %}"><img class="img-responsive center-block" src="{{item.item.image.img.url}}" alt="{{item.item.image.alt}}" /></a></td>
            <td>{{item.item_title}}</td>
            <td>{{item.count}}</td>
            <td><span class="orderpage_table__price">{{item.item_price}}</span></td>
            {% if cart.items_discount %}
            <td><span class="orderpage_table__sales">(-{{cart.items_discount}}%)</span> <span class="orderpage_table__price">{{item.item_price|with_discount:cart.items_discount}}</span></td>
            {% endif %}
        </tr>
        {% endfor %}
        <tr>
            <td class="orderpage_table__last" colspan="5">
                <ul class="orderpage_table__last-list list-unstyled">
                    <li class="list-item left-item"><a class="item-link" href="{% url 'cart-detail' %}">Изменить</a></li>
                    <li class="list-item right-item">Итого {% if cart.items_discount %}<span class="orderpage_table__sales">(со скидкой):</span>{% endif %} <span class="orderpage_table__price">{{cart.items_price_with_discount}}</span></li>
                </ul>
            </td>
        </tr>
    </tbody>
</table>    <!-- /.orderpage_table -->

main/templates/main/order-create.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load main_tags %}


{% block content %}
    <header class="header"></header>
    <div class="main">
        <div class="container">
            <div class="row">
                <div class="pathway text-uppercase col-lg-12">
                    <a class="pathway_link" href="{% url 'cart-detail' %}">Ваш заказ</a> &gt;&gt; оформление заказа
                </div>  <!-- /.pathway -->
            </div>  <!-- /.row -->
            
            <div class="row">
                <div class="title-holder col-lg-12">
                    <h1>Оформление заказа</h1>
                </div>  <!-- /.title-holder -->
            </div>  <!-- /.row -->
            
            <div class="orderpage text-center row">
                    <div class="orderpage-table center-block col-md-8">
                        <div class="orderpage_table-holder table-responsive" id="table-cart">
                            {% include 'main/order-create-cart.html' with cart=cart %}
                        </div>  <!-- /.table-responsive -->
                    </div>  <!-- /.orderpage-table -->
                    
                    <form class="col-lg-12" action="" method="post" id="create-order">
                        {% csrf_token %} 
                        <div class="orderpage_title text-uppercase">Выберите вариант доставки</div>
                        
                        <ul class="orderpage_list list-unstyled">
                            <li class="orderpage_list__item">
                                <input id="delivery_1" class="radio-button" type="radio" value="0" name="delivery_type" checked="checked" />
                                <label class="orderpage_label" for="delivery_1">Самовывоз</label>
                            </li>
                            <li class="orderpage_list__item">
                                <input id="delivery_2" class="radio-button" type="radio" value="1" name="delivery_type" />
                                <label class="orderpage_label" for="delivery_2">Бесплатная доставка по г. Казани</label>
                            </li>
                        </ul>   <!-- /.orderpage_list -->
                        
                        <div class="orderpage_title text-uppercase">Выберите способ оплаты</div>
                        
                        <ul class="orderpage_list list-unstyled">
                            <li class="orderpage_list__item i-icon i-cash">
                                <input id="payment_1" class="radio-button" type="radio" value="0" name="payment_type" checked="checked" />
                                <label class="orderpage_label" for="payment_1">Наличными</label>
                            </li>
                            <li class="orderpage_list__item i-icon i-paypal">
                                <input id="payment_2" class="radio-button" type="radio" value="2" name="payment_type" />
                                <label class="orderpage_label" for="payment_2">Электронными деньгами онлайн</label>
                            </li>
                            <li class="orderpage_list__item i-icon i-card">
                                <input id="payment_3" class="radio-button" type="radio" value="1" name="payment_type" />
                                <label class="orderpage_label" for="payment_3">Банковской картой онлайн</label>
                            </li>
                        </ul>   <!-- /.orderpage_list -->
                        
                        <div class="orderpage_title text-uppercase">заполните информацию 
                        {% if not user.is_authenticated %}
                        или <a class="orderpage_title__link" href="#" data-toggle="modal" data-target="#login">авторизуйтесь</a> / <a class="orderpage_title__link" href="#" data-toggle="modal" data-target="#registration">зарегистрируйтесь</a>
                        {% endif %}
                        </div>
                        <div class="orderpage_title_discount">
                            {% if discount_auth %}
                            после авторизации вы получите скидку {{discount_auth.amount}}% на все товары нашего магазина
                            {% endif %}
                        </div>

                        {{form.non_field_errors}}
                        
                        <ul class="orderpage_form center-block col-md-6 list-unstyled">
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.first_name.label}}</label>
                                {{form.first_name.errors}}
                                {{form.first_name}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.last_name.label}}</label>
                                {{form.last_name.errors}}
                                {{form.last_name}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.phone.label}}</label>
                                {{form.phone.errors}}
                                {{form.phone}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.email.label}}</label>
                                {{form.email.errors}}
                                {{form.email}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.delivery.label}}</label>
                                {{form.delivery.errors}}
                                {{form.delivery}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.delivery_date.label}}</label>
                                {{form.delivery_date.errors}}
                                {{form.delivery_date}}
                                {{form.delivery_date_widget}}
                            </li>
                            <li class="orderpage_form__item">
                                <label class="order_list__item-label">{{form.note.label}}</label>
                                {{form.note.errors}}
                                {{form.note}}
                            </li>
                            <li class="orderpage_form__item">
                                <input class="submit-item common-style" type="submit" value="Оформить заказ" />
                            </li>   

                        </ul>   <!-- /.orderpage_form -->   
                    </form>
                </div>  <!-- /.orderpage -->                
            </div>  <!-- /.row -->              
        </div>  <!-- /.container -->
    </div>  <!-- /.main -->
<br>
<br>
<br>
{% endblock %}

{% block js_extra %}
{{block.super}}
<script type="text/javascript">
    setInterval(function (){
        $("#id_delivery_date").toggleClass('delivery_date_mark_visible')
    },1000);
</script>
{% endblock %}